### ISSUE TITLE
Finish with any `FromIterator` type

### ISSUE THREAD

**Issue by jRimbault** [smol-rs/easy-parallel#6]
Would it be possible/desirable for `finish` (and `run`) to behave like `collect` ?

By replacing this : 

https://github.com/smol-rs/easy-parallel/blob/5048c696333c9c6c6e002a74b7cba97b005aa8c1/src/lib.rs#L244-L248 with something like :

```rust
pub fn finish<F, R, I>(self, f: F) -> (I, R)
where
    F: FnOnce() -> R,
    T: Send + 'a,
    I: std::iter::FromIterator<T>
{
    /* ... */
    let results: I = receivers.into_iter()
        .map(|receiver| receiver.recv().unwrap())
        .collect();
    /* ... */
}
```

Maybe by adding a generic `collect` consuming method (like `run`), which would then be used internally by `finish` (without changing its signature) ?

**Comment by taiki-e** [comment]
> adding a generic `collect` consuming method

Seems a good idea.
