### ISSUE TITLE
Unnecessary `T: Default` bound on `Default` implementation.

### ISSUE THREAD

**Issue by steffahn** [smol-rs/easy-parallel#7]
The derived `Default` implementation, as [documented  here](https://docs.rs/easy-parallel/3.1.0/easy_parallel/struct.Parallel.html#impl-Default), places an unnecessary `T: Default` bound. This can be fixed by using a manual implementation instead (which could just call `Parallel::new()`).

**Comment by taiki-e** [comment]
Done in 3.2.0
